name: yggdrasil_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  geolocator: ^14.0.2
  google_fonts: ^6.3.1
  http: ^1.5.0
  mobile_scanner: ^7.1.2
  permission_handler: ^12.0.1
  pretty_qr_code: ^3.5.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Icons/
  