name: yggdrasil_app
description: "Floresta 4.0"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.10.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  mobile_scanner: ^7.1.2
  permission_handler: ^12.0.1
  pretty_qr_code: ^3.5.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Icons/
    - assets/images/mascote/
  

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/Icons/laucher_Icons/icon-512x512-android.png"
  image_path_ios: "assets/Icons/laucher_Icons/icon-1024x1024-ios.png"

  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/Icons/laucher_Icons/icon-adaptative-background-432x432.png"  # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/Icons/laucher_Icons/icon-adaptative-foreground-432x432.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/Icons/laucher_Icons/adaptative-icon-monochome-412x412.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
